image_files = [
    "C:/Users/cgs/Documents/Data/3D-GeoInfo-2025/data/2_rescaled_data/5_cm/images/s3_p1.tif"
]
predict_tile = true
patch_size = 1000
patch_overlap = 0.2

[prediction_export]
output_folder = "C:/Users/cgs/Documents/Data/3D-GeoInfo-2025/data/4_predictions/5_cm/baseline"
output_file_name = "test_predictions.csv"