image_files = [
    "G:/3D-GeoInfo-2025/data/2_rescaled_data/7_5_cm/images/s3_p1.tif"
]
predict_tile = true
patch_size = 667
patch_overlap = 0.2

[prediction_export]
output_folder = "G:/3D-GeoInfo-2025/data/4_predictions/7_5_cm/baseline"
output_file_name = "test_predictions.csv"