base_dir = "C:/Users/cgs/Documents/Data/3D-GeoInfo-2025/data"
tmp_dir = "./tmp"
patch_size = 2000
patch_overlap = 0.2
image_folder = "./2_rescaled_data/2_5_cm/images"
train_annotation_files = [
    "./2_rescaled_data/2_5_cm/labels/manual_labeling/s1_p1_ext_ml_coco.json",
]
test_annotation_files = [
    "./2_rescaled_data/2_5_cm/labels/manual_labeling/s3_p1_coco.json"
]
epochs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
seeds = [0, 1, 2, 3, 4]
learning_rate = 0.0001
checkpoint_dir = "./3_checkpoints/2_5_cm/manual_labeling_ext"

[prediction_export]
output_folder = "./4_predictions/2_5_cm/manual_labeling_ext"
